-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.languages
(
    language_id uuid NOT NULL,
    language text NOT NULL,
    PRIMARY KEY (language_id)
);

CREATE TABLE IF NOT EXISTS public.translations
(
    translation_id uuid NOT NULL,
    language_id uuid NOT NULL,
    morning text NOT NULL,
    afternoon text NOT NULL,
    evening text NOT NULL,
    PRIMARY KEY (translation_id)
);

ALTER TABLE IF EXISTS public.translations
    ADD CONSTRAINT "language_id_FK" FOREIGN KEY (language_id)
    REFERENCES public.languages (language_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;